### ISSUE TITLE
Ability to change the url of imageupload in settings

### ISSUE THREAD

**Issue by mvdwaeter** [adi-/django-markdownx#12]
The url of the preview view is changeable because it's retrieved from a data-attribute of the widget, however the url of the image upload view isn't as it is hardcoded in the javascript.

Shall I make a pull-request for this?

**Comment by adi-** [comment]
Yeah, didn't know that someone would like to have custom url. I will get into this in the weekend probably.

**Comment by adi-** [comment]
Merged. Closing...
