### ISSUE TITLE
Documentation about most used markdown extension

### ISSUE THREAD

**Issue by mvdwaeter** [adi-/django-markdownx#14]
I propose to add a  small section to the documentation about markup extensions.

1. An example use of MARKDOWNX_MARKDOWN_EXTENSIONS = ['markdown.extensions.nl2br', ]
which in imho is the most wanted extension.
2. a link to a page where people can [learn more about markdown extensions](https://pythonhosted.org/Markdown/extensions/index.html)

**Comment by adi-** [comment]
Can do :)
