### ISSUE TITLE
Make rendering the markdown abstractable

### ISSUE THREAD

**Issue by mvdwaeter** [adi-/django-markdownx#15]
I'd propose a new settings witch holds the path to the markdownify definition:

    # Markdownify
    MARKDOWNX_FUNCTION = getattr(settings, 'MARKDOWNX_FUNCTION', 'markdownx.utils.markdownify_default')

In utils.py you'd then have:

    def markdownify_default(content):
        return markdown.markdown(
                        content,
                        extensions=MARKDOWNX_MARKDOWN_EXTENSIONS,
                        extension_configs=MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS)

And the post definition of MarkdownifyView will load request.POST['content'] into that function.

The idea is that you now have an option to keep the code DRY, because you can refer to the exact same markdownify function (e.g. for database caching of the rendered html).

**Comment by adi-** [comment]
Interesting idea. Will look at this soon. Of course,  thank you for your input! Do u wanna implement it by yourself?

**Comment by adi-** [comment]
However, I am curious, why would you like to display cached content in the editor?

**Comment by adi-** [comment]
> However, I am curious, why would you like to display cached content in the editor?

Ok, I think I have an answer for my question :) Nvmd, your suggestion is in fact very helpfull. This needs to be implemented!

**Comment by mvdwaeter** [comment]
Sorry, somehow I didn't got notifications on this thread last year. Thanks for implementing it.
