### ISSUE TITLE
AdminMarkdownxWidget subclasses cannot be used with formfield_overrides

### ISSUE THREAD

**Issue by mariuszjamro** [adi-/django-markdownx#16]
You can subclass `AdminMarkdownxWidget` (for example to change css/js) and use that widget in `formfield_overrides` like that:

	class CustomMarkdownWidget(AdminMarkdownxWidget):
		class Media:
			css = {
				'all': ('other.css',)
			}
			js = (
				'other.js',
			)

	class BaseAdmin(admin.ModelAdmin):

		formfield_overrides = {
			MarkdownxField: {'widget': CustomMarkdownWidget}
		}

In that case the new widget won't be used. Instead the widget will be overwritten with `markdownx.widgets.MarkdownxWidget`. This happens because in `markdownx\fields.py` the`MarkdownxFormField` is checking if class of current widget is `!= AdminMarkdownxWidget`. If the condition is true it overrides the widget with `MarkdownxWidget` (the non-admin one):

	class MarkdownxFormField(forms.CharField):

		def __init__(self, *args, **kwargs):
			super(MarkdownxFormField, self).__init__(*args, **kwargs)

			if self.widget.__class__ != AdminMarkdownxWidget:
				self.widget = MarkdownxWidget()

It should check if self.widget.__class__  is not subclass of MarkdownxWidget instead of the `!=` comparison.

**Comment by adi-** [comment]
Thanx!
