### ISSUE TITLE
Preview and image insertion with CSRF_COOKIE_HTTPONLY = True

### ISSUE THREAD

**Issue by Zahtu** [adi-/django-markdownx#21]
Hi, 
i'm currently using your package for writing blog posts in markdown. Having set `CSRF_COOKIE_HTTPONLY = True` in my settings.py file, the preview and image insertion don't seem to work. 

I guess it has to do with the retrieval of the csrftoken in your javascript as this returns empty in this case.

**Comment by adi-** [comment]
https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY

**Comment by Zahtu** [comment]
Sorry, i don't quite understand. I have set this to true, and the behavior of the markdownx-widget changed.

**Comment by timgraham** [comment]
I was looking at using this package on djangoproject.com and also ran into this issue. If you don't want to change this, it could be useful to document that the package doesn't work with `CSRF_COOKIE_HTTPONLY=True` but is there is reason the CSRF token couldn't be retrieved from a form input instead?

**Comment by adi-** [comment]
In my opinion `CSRF_COOKIE_HTTPONLY = True` is a misleading security advice. Look also at this https://groups.google.com/forum/#!topic/django-developers/nXjfLd8ba5k to get the idea.

However, if HTTP COOKIE is helping you out with something else, it could be a point to support injecting token into hidden input field.
