### ISSUE TITLE
Cannot upload gif files

### ISSUE THREAD

**Issue by SalahAdDin** [adi-/django-markdownx#24]
I'm trying to upload gif but i can't do it.
I put this in settings:
```
MARKDOWNX_UPLOAD_CONTENT_TYPES = ['image/jpeg', 'image/png', 'image/gif']
```

How can we make a propperly configuration to upload gif?

**Comment by adi-** [comment]
Yeah, animated gifs are pain in the ass in PIL. Especially if you want to scale them. Currently, only the first frame is saved and display, so your observations are correct. I do not see any good and fast option to fix your issue.

**Comment by camilonova** [comment]
I agree we should stay away from gifs. You can upload it somewhere else (giphy.com) and paste the url.

**Comment by adi-** [comment]
Closing...

**Comment by jaywink** [comment]
Does this year ago resolution still stand? I made [a patch](https://github.com/jaywink/django-markdownx/commit/e42748b9e411550ba4a70287cc006824a7199887) for myself that works by just skipping the scaling, so it goes the SVG route. Gifs upload perfectly, though I'm not sure if there is something else that might need doing. Except prepare to buy a bigger disk ;)
