### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by StudentDawid** [adi-/django-markdownx#25]
Hello, can you help me ? :smile: 
I don`t know how to show my markdown data on template.
I have something like
```
<h1>{{ post.title }}</h1>
<p>{{ post.text }}</p>
<p>{{ post.markdown }}</p>
```

and i see only 
```
title
text
#text1 ![](/media/markdownx/ab3bfac7-7509-411a-96c8-11aebc20b873.jpg)
```
but i want compiled version (with image) 
Could you explain how templates with markdownx work ? Or create some exaple with that ? :smile:

**Comment by sujan-sube** [comment]
Hi StudentDwid,

I was able to get it working by rendering the markdown in views.py then passing it to templates. I wanted to render the text in the object post.text then pass it to templates to render blog/post_list.html.This is how it looks:

**views.py**:
```Python
from markdownx.utils import markdownify

posts = Post.objects.filter(published_date__lte=timezone.now())
def post_list(request):
    for post in posts:
        post.text = markdownify(post.text)
    return render(request, 'blog/post_list.html', {'posts': posts})
```

**post_list.html**:
```Python
        <div class="post">
            <h1>
                <a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
            </h1>
            <p>{{ post.text|safe }}</p>
        </div>
```

**Comment by StudentDawid** [comment]
It`s work, Thank you :smile:

**Comment by sujan-sube** [comment]
No problem, glad its working for you. :smiley:

**Comment by oskarko** [comment]
this doesn't work for me :(

**Comment by oskarko** [comment]
I see this code in my post...

<h2>hola!</h2>
<pre><code>function(){ 
a = 4; 
}
</code></pre>
<p><img alt="imageUna" src="/media/markdownx/e0fea44e-cec3-4a43-9e92-2338e34b3b48.jpg" /></p>

but I can't see the image

**Comment by oskarko** [comment]
I have a paginator with this

class PostListView(ListView):
    model = Post
    paginate_by = 5
    template_name = 'post_list.html'
    queryset = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

and I can't do markdownify(post.text)

**Comment by oskarko** [comment]
I got it!

class PostListView(ListView):
    model = Post
    paginate_by = 5
    template_name = 'post_list.html'

# change my query before returns
    def get_queryset(self):
        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        for post in posts:
            post.text = markdownify(post.text)
        return posts

**Comment by StanleyDerLurch** [comment]
Is there a solution for "unmarkdownify"?
I have an update_view and get the plain HTML text back on editing. It is not usable for other users

**Comment by 0-afflatus** [comment]
sujan-sube this works for me - I'm new to markdownx as of 2 days ago. This example helped me get things working the way I like. May I suggest adding it to the docs? I think it deals with #74 too.
