### ISSUE TITLE
Unable to use custom widget in templates

### ISSUE THREAD

**Issue by sujan-sube** [adi-/django-markdownx#26]
I added markdownx/widget.html to my TEMPLATES_DIR but I am still unable to see the changes I have made. However when I make changes to widget.html found in markdownx\templates\markdownx\widget.html that is found in the package, I am able to change it.
This is how my project structure looks like:

![image](https://cloud.githubusercontent.com/assets/14242885/16565319/7f61659c-41da-11e6-8150-bf138c77e84e.png)

I am trying to have the side-by-side panels as shown in the picture on the README.md of this repo. Also, I'm using Django 1.9 and python 3.5.1.

**Comment by adi-** [comment]
It should work. Please double check your templates dir in settings. When you think it is fine, use Django Debug Toolbar to debug the problems.

**Comment by sujan-sube** [comment]
Thank you adi! Its working now. My settings file was pointing to PROJECT_DIR/templates instead of PROJECT_DIR/APP_NAME/templates
