### ISSUE TITLE
Opening editor to the width of <div>

### ISSUE THREAD

**Issue by theced7** [adi-/django-markdownx#29]
Hi,

first of all: Thank you very much for this great django package! I was desperately searching for a decent editor and this just blew all of my expectations out of the water! 

One small thing though: 
<img width="960" alt="markdownx" src="https://cloud.githubusercontent.com/assets/11862606/17836944/3ed3e8ba-67a5-11e6-899b-737b5a7ae1fb.PNG">

Is it possible to aviod that gap i.e. to extend the editor's width? 

I'm using this very basic template from the readme, basically the editor should just be as wide as the <div> container:
```
<div class="markdownx row">
<div class="col-md-6">
    {{ markdownx_editor }}
</div>
<div class="col-md-6">
<div class="markdownx-preview"></div>
</div>
</div>
~
```

I'm using `MarkdownxFormField()` within a ModelForm.

On a sidenote: The editor is not resizeable at all (i.e. by drag the frame). Is that an issue on my side?

**Comment by adi-** [comment]
Thanks!

The problem you describe is simply fixable. You need to use proper styling. Just take a look at:

```html
<div class="col-md-6">
    {{ markdownx_editor }}
</div>
```
`{{ markdownx_editor }}` will return `<textarea>` which should be styled as:

```css
textarea {
  width: 100%;
}
```

> On a sidenote: The editor is not resizeable at all (i.e. by drag the frame). Is that an issue on my side?

No, just set:

```css
textarea {
  resize:both;
}
```

More at www.w3schools.com/cssref/css3_pr_resize.asp

**Comment by theced7** [comment]
Ha! Thank you very much! I'm not at all familiar with CSS, so that was a big help!
