### ISSUE TITLE
Top toolbar would be awesome!

### ISSUE THREAD

**Issue by queiroz** [adi-/django-markdownx#30]
Something like...
<img width="837" alt="screen shot 2016-09-15 at 11 58 43" src="https://cloud.githubusercontent.com/assets/670685/18549345/d0573c8e-7b45-11e6-87f4-2dc6e7c5b75c.png">

**Comment by adi-** [comment]
Damn, I have removed one sentence from the readme some time ago. It was like "all UI widgets are unwelcome. Django-markdownx is not a shitty MS Word web editor imitation". 

So, answering your questions: no, sorry.

**Comment by agusmakmun** [comment]
Hello @queiroz, this [django-markdownx](https://github.com/adi-/django-markdownx) was inspired me to create same markdown editor with **Top toolbar**, with using API Imgur to upload an image, but also provide custom uploader at **[wiki page](https://github.com/agusmakmun/dracos-markdown-editor/wiki)**
For more info, you can checkout at https://github.com/agusmakmun/dracos-markdown-editor

Thank so much for @adi-

**Comment by adi-** [comment]
From my experience, JS toolbars like that only bring frustration. I haven't seen any that work as expected. Markdown was also designed for *power* users, that know what they do. It is much simpler that way.
