### ISSUE TITLE
Using inline HTML

### ISSUE THREAD

**Issue by wasabigeek** [adi-/django-markdownx#31]
Hi,

I've setup markdownx in the admin, but when writing inline HTML, it gets escaped e.g. `<a class="btn-contact">` becomes `&lt;a class="btn-contact"&gt;`. Is this expected, and is there another way around it?

I'm using django-markdownx==1.3.

**Comment by adi-** [comment]
You should use markdown code syntax. https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

Dnia 12.11.2016 o godz. 07:58 Nicholas <notifications@github.com> napisał(a):

**Comment by wasabigeek** [comment]
"You can also use raw HTML in your Markdown, and it'll mostly work pretty
well."

**Comment by adi-** [comment]
You CAN use raw html in your markdown compiled with pyton. Read more about it here: https://pythonhosted.org/Markdown/reference.html

Dnia 12.11.2016 o godz. 13:18 Nicholas <notifications@github.com> napisał(a):

> "You can also use raw HTML in your Markdown, and it'll mostly work pretty
> well."
>

**Comment by wasabigeek** [comment]
But that's not what I experienced as mentioned. Steps to reproduce:
- add markdownx field to model and make available in admin
- enter raw html into the field e.g. `<a class="btn-contact">`
- in template, using {{field|markdownify|safe}} displays <a class="btn-contact"> while removing safe displays `&lt;a class="btn-contact"&gt;`-

**Comment by adi-** [comment]
Ok, so I need to check it. Will reply after the weekend. 

Dnia 12.11.2016 o godz. 14:23 Nicholas <notifications@github.com> napisał(a):

**Comment by adi-** [comment]
If you want to output raw html go to https://pythonhosted.org/Markdown/reference.html#safe_mode

**Comment by adi-** [comment]
This is NOT normal use, so I don't think it will be supported in django-markdownx. But of course, you may overwrite `markdownify` function.
