### ISSUE TITLE
absolute path for images

### ISSUE THREAD

**Issue by oskarko** [adi-/django-markdownx#34]
Hi!
Is there any way to add images with absolute path? I'm having issues with relative path.

**Comment by adi-** [comment]
Ha, good question. In general, the problem with images and paths is buried inside the Markdown itself. When you want to display an image, you need to use tag i.e. `![](/media/markdownx/33bd4794-18af-4a80-b716-36c65e59cb14.png)` which is text link in fact. 

The only way (I think) to change this url on the fly is using some custom tag which will be "transformed" when Markdown is compiled. I have used this technique once, writing custom Markdown `Extension` which in short is a regexp function that basically does what you want to achieve. More info here https://pythonhosted.org/Markdown/extensions/api.html

I know this is completely abstract but django-markdownx wasn't designed for absolute paths in mind, or even switching between absolute/relative. Let's leave this ticket open. Maybe I will figure out some simple mechanism in the future, 'aight?

**Comment by adi-** [comment]
Found something like: http://facelessuser.github.io/pymdown-extensions/extensions/pathconverter/
