### ISSUE TITLE
403 error when deployed to production using CSRF_COOKIE_HTTPONLY = True for preview event updates

### ISSUE THREAD

**Issue by gibbymt** [adi-/django-markdownx#35]
I tracked an issue where preview events were not triggering updates to the preview form that only appeared when I deployed to heroku. It appears that when CSRF_COOKIE_HTTPONLY = True the events will not be able to update the page due to a 403 error.

**Comment by adi-** [comment]
Can't help you, because app is not working. Try to open debug console and see what errors are shown (if it is JS related).

**Comment by jcaguirre89** [comment]
Was this solved?
