### ISSUE TITLE
self.attrs problem

### ISSUE THREAD

**Issue by sh0416** [adi-/django-markdownx#42]
I have a problem to develop using this package.

```python
class MyModelForm(forms.ModelForm):
  class Meta:
    model = MyModel
    field_classes = {'content': MarkdownxFormField,}
    widgets = {'content': MarkdowxWidget(attrs={'class':'form-control'})}
```

So I override your function 'render' and merge attrs and self.attrs and it works.
Also, I think it will handle this problem.

```python
class MarkdownxWidgetImproved(MarkdownxWidget):
  def render(self, name, value, attrs=None):
    allAttrs = {**attrs, **self.attrs}
    return super(MarkdownxWidgetImproved, self).render(name, value, allAttrs)
```

I request pull, but canceled because I expect that that code doesn't work when attrs is None.

**Comment by adi-** [comment]
Please paste more details. What kind of problems you are experiencing? Have you checked if markdown.css and markdown.js are downloaded correctly?

**Comment by sh0416** [comment]
When I use your pure `MarkdownxWidget`, 'form-control' doesn't appear in the HTML file. However, I used that class `MarkdownxWidgetImproved`, 'form-control' appear in the HTML file. template is just `{{ form.content }}`. Other functionality is well working, just that feature doesn't work.

**Comment by adi-** [comment]
Have u checked it with v1.7?

**Comment by adi-** [comment]
It was published on Saturday.

**Comment by sh0416** [comment]
Yes, I take package before 3 hours ago. I'll give you some example core for this. wait a minute.

**Comment by sh0416** [comment]
See This. [http://www.geekble.net:8000/](http://www.geekble.net:8000/)
Code is here.

**Comment by sh0416** [comment]
You doesn't mention about this kind of usage, but I think this is also well work.. :)

**Comment by adi-** [comment]
Yes, I have spotted the bug. Fix is on the way!

**Comment by adi-** [comment]
https://github.com/adi-/django-markdownx/releases/tag/v1.7.1 should fix your issue.

**Comment by adi-** [comment]
It is already on PyPi
