### ISSUE TITLE
Chance to "unmarkdownify" on update view

### ISSUE THREAD

**Issue by StanleyDerLurch** [adi-/django-markdownx#48]
Hi,

will there be a solution for update views? If I update one article, I get plain HTML Text and this is exhausting  for normal users..

**Comment by xenatisch** [comment]
I am not quite certain as to what you're after. Could you please provide a more detailed scenario? 

You are not forced to do anything. You can use markdown to save the contents either in your database or in a file, and read them back as markdown and convert them just before serving, or cache the conversions, or serve both converted and non-converted material. 

Again, I'm just speculating on your problem. Give us more. Outline the problem and give more details, and I'll be happy to provide you with additional help.

**Comment by StanleyDerLurch** [comment]
actually it's quite easy ^^
if I create a post with
`content = markdownify(content)`
and on update post I get the plain Text with HTML tags...

For example (on create):
`###heading
blatext`

on update I get:
`<h3>heading</h3><p>blatext</p>`

**Comment by jaywink** [comment]
@StanleyDerLurch Simple. Store the content as is and when rendering do `markdownify(content)`. If you want users to edit it later, you must keep the original.

**Comment by xenatisch** [comment]
@jaywink That's precisely what I said, but I thought maybe I'm not getting the point. 

@StanleyDerLurch Are you actually saving the data as HTML? You should really be saving everything as MD and then serve them as HTML.

**Comment by xenatisch** [comment]
Any response to this, or shall I go ahead and close this issue?

**Comment by adi-** [comment]
I also think that this is ridiculous. I think that this isse comes from a lack of knowledge rather than real need. Closing this one is the best we can do about it :)
