### ISSUE TITLE
Storing the pre-rendered markdown

### ISSUE THREAD

**Issue by yozel** [adi-/django-markdownx#5]
It would be good that storing the pre-rendered markdown in the db, since content only changes when markup field changed. Why should we render the markdown content over and over?

**Comment by adi-** [comment]
This is only the editor, so you mainly use it to alter markup. I don't see any problem when you store rendered markdown in the model in your app to display it directly to the user. This is out of the editor scope.

Is that what you were asking for?

**Comment by yozel** [comment]
Yes this is what i was asking for. I had wanted something like django-markupfield. But as I understand it, you make this as only a editor and you want to keep this simple.

By the way, sorry for spamming your project with my resultless issues. Your project is awesome and so minimalist, thank you for your effort.

**Comment by adi-** [comment]
No problem, I'm glad I could help.
