### ISSUE TITLE
Compatibility with Django 1.11

### ISSUE THREAD

**Issue by aaugustin** [adi-/django-markdownx#50]
Django 1.11 provides template-based widget rendering.

That's good news, because django-markdownx no longer needs to roll its own, but also bad news, because the current implementation breaks.

I made a quick implementation that appears to work on Django 1.11b1 with the following changes.

1. Create a `widget2.html` template next to `widget.html` with the following content:

```html
<div class="markdownx">
    {% include 'django/forms/widgets/textarea.html' %}
    <div class="markdownx-preview"></div>
</div>
```

2. Replace the implementation of `MarkdownxWidget` with:

```python
class MarkdownxWidget(forms.Textarea):
    template_name = 'markdownx/widget2.html'

    def get_context(self, name, value, attrs=None):
        if attrs is None:
            attrs = {}

        if 'class' in attrs:
            attrs['class'] += ' markdownx-editor'
        else:
            attrs.update({'class': 'markdownx-editor'})

        attrs['data-markdownx-editor-resizable'] = MARKDOWNX_EDITOR_RESIZABLE
        attrs['data-markdownx-urls-path'] = MARKDOWNX_URLS_PATH
        attrs['data-markdownx-upload-urls-path'] = MARKDOWNX_UPLOAD_URLS_PATH

        return super(MarkdownxWidget, self).get_context(name, value, attrs)

    class Media:
        js = (
            'markdownx/js/markdownx.js',
        )
```

In order to keep compatibility with earlier version of django, you'll probably want to do something like:

```python
class MarkdownxWidget(forms.Textarea):
    if django.VERSION[:2] >= (1, 11):
        """new implementation goes here"""
    else:
        """current implementation stays here"""
```

It's a bit too late here to turn this suggestion into a proper pull request, but I hope this helps anyway!

**Comment by xenatisch** [comment]
Yes... I know! There are quite a few backward compatibility matters that need to be taken care of; and this is one more. This is exactly the reason why we have started working on Django 1.11 quite a bit in advance.

And I'll get there; eventually. 

Meanwhile, I'm working on a the docs, pure JS, Django 1.11 compatibility, 4 more locale definitions, and a few clean ups in a [separate branch for version 2](https://github.com/adi-/django-markdownx/tree/v.2%2Bdocs). You're welcome to join the party!

What you have highlighted is in my to do list, and I will implement the changes once I get there - that is, of course, if you don't beat me to it. ;)
