### ISSUE TITLE
How to use the custom widget in templates?

### ISSUE THREAD

**Issue by hiddensorrow** [adi-/django-markdownx#54]
Actually I'm new to django and Python.
I added the markdownx/widget.html to my TEMPLATES_DIR according to the instruction:
![image](https://cloud.githubusercontent.com/assets/13173323/24234935/cfe7a8ea-0fd5-11e7-9ab9-a02974e5ca3d.png)
but it didn't make any sense. It could not show as the preview image, and just looked as below:
![image](https://cloud.githubusercontent.com/assets/13173323/24234967/f0c8d8d6-0fd5-11e7-9b2a-3b9da710fe2c.png)
I've tried to use django debug toolbar, which showed that the widget.html had been rendered:
![image](https://cloud.githubusercontent.com/assets/13173323/24235049/59633c38-0fd6-11e7-972e-4775c17b7928.png)
But I still don't understand where it went wrong...Did I missing something or misunderstood the method to change the custom widget? If so , plz tell me:)
Could any one help me...
Thx!
ps: My Django version is 1.8.8 and the Python version is 3.5.0

**Comment by adi-** [comment]
Hi @hiddensorrow,

custom widget works only in normal views, the ones outside of Django Admin Pages. Django Admin is using its own styles, so normally adding Bootstrap just won't work there. If you want to fight that issue you have two options in my opinion:
1. write your own styles overriding `static/markdownx/admin/css/markdownx.css`
2. Use bootstrap admin plugin. You could try i.e. https://github.com/django-admin-bootstrapped/django-admin-bootstrapped. I haven't tried it, but should work.

**Comment by hiddensorrow** [comment]
@adi- Thank you :P
