### ISSUE TITLE
build_attrs() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by mrgaolei** [adi-/django-markdownx#55]
```python
Class Model1(models.Model):
    content = MarkdownxField(u"Content")

@admin.register(Model1)
class Model1Admin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': AdminMarkdownxWidget}
    }
```

Got `TypeError`:
`build_attrs() got an unexpected keyword argument 'name'`
in widgets.py line 15

**Comment by xenatisch** [comment]
What version of Django you're using? 1.11b?

**Comment by mrgaolei** [comment]
1.11rc1
I'm working to migrate to 1.11

**Comment by xenatisch** [comment]
You realise that's the beta version, right?

We have solved that problem in [version 2](https://github.com/adi-/django-markdownx/tree/v.2%2Bdocs), which will be released soon. See issue #52 for additional information and the fix.
